org: raylin9981
app: aws-node
console: true
service: apollo-lambda
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MYSQL_DATABASE: ${param:MYSQL_DATABASE}
params:
  prod:
    MYSQL_DATABASE: prod
  dev:
    MYSQL_DATABASE: test
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true


  
